// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gkjyajysblgdxujbdwxc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdranlhanlzYmxnZHh1amJkd3hjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDMxMjcwNTksImV4cCI6MjA1ODcwMzA1OX0.-wSgfH1Rzsk3PGFuITiNBlLel4QgjO-tTKn5k16N1LI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});